import { DefaultTheme } from 'styled-components';
export declare const breakpoints: string[];
export declare const mediaQueries: string[];
export declare const space: number[];
export declare const font = "'Montserrat','Helvetica Neue',Helvetica,Arial,sans-serif";
export declare const fontSizes: number[];
export declare const medium = 500;
export declare const bold = 700;
export declare const regular = 500;
export declare const fontWeights: {
    medium: number;
    bold: number;
    regular: number;
};
export declare const lineHeights: {
    standard: number;
    display: number;
};
declare const colors: {
    black: string;
    white: string;
    text: string;
    blue: string;
    lightBlue: string;
    darkBlue: string;
    gray: string;
    lightGray: string;
    buttonGray: string;
    borderGray: string;
    darkGray: string;
    green: string;
    lightGreen: string;
    darkGreen: string;
    red: string;
    lightRed: string;
    darkRed: string;
    orange: string;
    darkOrange: string;
    lightOrange: string;
    purple: string;
    lightPurple: string;
    yellow: string;
    lightYellow: string;
    pink: string;
    darkPurple: string;
};
export { colors };
export declare const radii: number[];
export declare const radius = "2px";
export declare const maxContainerWidth = "1280px";
export declare const boxShadows: string[];
export declare const textShadows: {
    sm: string;
    md: string;
};
export declare const duration: {
    fast: string;
    normal: string;
    slow: string;
    slowest: string;
};
export declare const textStyles: import("../utils/createTextStyles").TextStyles;
export declare const colorStyles: import("../utils/createColorStyles").ColorStyles;
declare const theme: DefaultTheme;
export default theme;
