#!/bin/sh

if [ $CI ]
then
  echo In CI, skipping pre-commit checks.
  exit 0
fi

# Invoke the "rush prettier" custom command to reformat files whenever they
# are committed. The command is defined in common/config/rush/command-line.json
# and uses the "rush-prettier" autoinstaller.
node common/scripts/install-run-rush.js prettier || exit $?