const XS_VISIBLE_SLIDES = 1.1

const SM_VISIBLE_SLIDES = 2.1

const XS_VISIBLE_SLIDES_WIDTH = 768

const SM_VISIBLE_SLIDES_WIDTH = 1024

export { XS_VISIBLE_SLIDES, SM_VISIBLE_SLIDES, XS_VISIBLE_SLIDES_WIDTH, SM_VISIBLE_SLIDES_WIDTH }
