const XS_VISIBLE_SLIDES = 1.1

const SM_VISIBLE_SLIDES = 2.1

const XS_VISIBLE_SLIDES_WIDTH = 768

const SM_VISIBLE_SLIDES_WIDTH = 1024

const MEDIA_QUERY_MATCH = `(max-width: ${SM_VISIBLE_SLIDES_WIDTH}px) and (min-width: ${XS_VISIBLE_SLIDES_WIDTH}px)`

export {
  XS_VISIBLE_SLIDES,
  SM_VISIBLE_SLIDES,
  XS_VISIBLE_SLIDES_WIDTH,
  SM_VISIBLE_SLIDES_WIDTH,
  MEDIA_QUERY_MATCH,
}
