export { default as Text } from './Text'
export { default as theme } from './theme'
export { default as legacyTheme } from './legacyTheme'
export { default as ThemeProvider } from './ThemeProvider'
export * from './theme'
