const fs = require('fs')
const path = require('path')

const dirname = path.join(__dirname, './components')
const icons = fs
  .readdirSync(dirname)
  .filter((filename) => /\.jsx$/.test(filename))
  .map((filename) => path.basename(filename, '.jsx'))

const template = (icons) => {
  const iconsToExport = icons
    // Don't include a line for the index file itself, since it's also in the components folder
    .filter((name) => name !== 'index')
    .map((name) => `export { default as ${name} } from './${name}.jsx'`)

  return iconsToExport.join('\n') + '\n'
}

const content = template(icons)

// Write to components folder (used by build)
const componentsFilename = path.join(__dirname, './components/index.js')
fs.writeFileSync(componentsFilename, content)

// Also write a development version to src that re-exports from components
const srcFilename = path.join(__dirname, './src/index.js')
const devContent = `// Re-export from components folder for development
// This file is auto-generated by create-index.js
export * from '../components'
`
fs.writeFileSync(srcFilename, devContent)
